### ISSUE TITLE
When User doesn´t have an Avatar getting User Information isn´t possible

### ISSUE THREAD

**Issue by Jeytastic** [HayateLaTech/OAuth2Discord#7] opened 2020-02-20 21:04 UTC
I am really enjoying your work and it helps me a lot. But when I try to authorize a User without an avatar `builder.getUser();` always throws the error: `org.json.JSONException: JSONObject["avatar"] not a string.` Can you help me with this, would really bring me forward. Thank you in advance and best wishes :)

**Comment by HayateLaTech** [comment] 2020-02-20 22:12
I'm glad that you enjoy this work, be aware though that I created this project way back (2 years ago) and actually kinda forgot about it - sorry for not maintaining it, it's not a good practice.

Over the years the Discord OAuth2 Docs have changed a bit - I'm not sure if these changes were the cause of your problem but you may want to revisit my code and look at the official discord developer documentations for reference:
[User Object (Discord Docs)](https://discordapp.com/developers/docs/resources/user)

And here's your starting point for customizing my library:
[The File + Line to start with which needs to be changed (very likely)](https://github.com/HayateLaTech/OAuth2Discord/blob/master/src/bell/oauth/discord/main/OAuthBuilder.java#L123)

I also advise that you can look at already existing forks of this project, maybe those have an updated version of my code that'll help you out ;D 
I myself can't get into updating all this myself because I need to prepare for exams and I currently don't have a working debug environment for this project. :c 

Good Luck! :D 
(The base idea of the OAuth2 flow is still the same sooo.. it should still all work somehow.. I also thought that the missing avatar bug has been fixed by a pull request in the past.. ;w;)

--> https://github.com/HayateLaTech/OAuth2Discord/pull/5

Are you sure that this problem isn't fixed? x3
(Do you use the latest version?) o:

**Comment by Jeytastic** [comment] 2020-02-21 12:22
Thank you very much for the fast and detailed answer, it really helped me a lot :)
After checking again the version I used, I found out I was using the probably oldest version you can find  on jitpack xD. So now now everything works fine. Good luck with your exams you can do this :D !

**Closed as completed** 2020-02-21 12:24 UTC
